CREATE DATABASE IF NOT EXISTS noisemap;

CREATE TABLE stations (
    station_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    geom geometry(Point, 4326) NOT NULL
);

CREATE TABLE IF NOT EXISTS noise_reading (
    reading_id BIGSERIAL PRIMARY KEY,
    station_id INT NOT NULL,
    ts_utc TIMESTAMPTZ NOT NULL,
    db_level NUMERIC(5, 2) NOT NULL,
    part_of_day TEXT,
    src_month DATE GENERATED ALWAYS AS (
        date_trunc('month', ts_utc AT TIME ZONE 'UTC') :: date
    ) STORED,
    CONSTRAINT fk_noise_station FOREIGN KEY (station_id) REFERENCES stations(station_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_part_of_day CHECK (
        part_of_day IN ('day', 'night')
        OR part_of_day IS NULL
    ),
    CONSTRAINT uq_noise_station_ts UNIQUE (station_id, ts_utc)
);

CREATE TABLE IF NOT EXISTS noise_level_d (
    station_id INT NOT NULL REFERENCES stations(station_id) ON DELETE CASCADE,
    d_kst DATE NOT NULL,
    -- дата (KST)
    laeq_day NUMERIC(6, 2),
    -- уже посчитанный LAeq за день
    laeq_night NUMERIC(6, 2),
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP,
    PRIMARY KEY (station_id, d_kst)
);

CREATE TABLE IF NOT EXISTS noise_level_h (
    station_id INT NOT NULL REFERENCES stations(station_id) ON DELETE CASCADE,
    ts_hour_kst TIMESTAMP NOT NULL,
    -- начало часа (KST)
    n_samples INT,
    laeq NUMERIC(6, 2) NOT NULL,
    -- LAeq за час
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP,
    PRIMARY KEY (station_id, ts_hour_kst)
);

CREATE INDEX IF NOT EXISTS idx_noise_reading_station_ts ON noise_reading (station_id, ts_utc);

CREATE INDEX idx_noise_ts ON noise_reading(ts_utc);

CREATE INDEX idx_noise_station ON noise_reading(station_id);