CREATE DATABASE IF NOT EXISTS noisemap;

CREATE TABLE stations (
    station_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    geom geometry(Point, 4326) NOT NULL
);

CREATE TABLE IF NOT EXISTS noise_reading (
    reading_id BIGSERIAL PRIMARY KEY,
    station_id INT NOT NULL,
    ts_utc TIMESTAMPTZ NOT NULL,
    db_level NUMERIC(5, 2) NOT NULL,
    part_of_day TEXT,
    src_month DATE GENERATED ALWAYS AS (
        date_trunc('month', ts_utc AT TIME ZONE 'UTC') :: date
    ) STORED,
    CONSTRAINT fk_noise_station FOREIGN KEY (station_id) REFERENCES stations(station_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_part_of_day CHECK (
        part_of_day IN ('day', 'night')
        OR part_of_day IS NULL
    ),
    CONSTRAINT uq_noise_station_ts UNIQUE (station_id, ts_utc)
);

-- Почасовая витрина по каждой станции (KST-час)
CREATE TABLE IF NOT EXISTS noise_level_h (
    station_id INT NOT NULL REFERENCES stations(station_id) ON DELETE CASCADE,
    ts_hour_kst TIMESTAMP NOT NULL,
    -- начало часа в KST
    n_samples INT NOT NULL,
    laeq NUMERIC(6, 2),
    -- эквивалентный уровень (энергетич. ср.)
    lmin NUMERIC(6, 2),
    lmax NUMERIC(6, 2),
    l10 NUMERIC(6, 2),
    l50 NUMERIC(6, 2),
    l90 NUMERIC(6, 2),
    src_month DATE,
    -- из сырых для удобства
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (station_id, ts_hour_kst)
);

CREATE INDEX IF NOT EXISTS idx_noise_level_h_month ON noise_level_h (src_month);

CREATE INDEX IF NOT EXISTS idx_noise_reading_station_ts ON noise_reading (station_id, ts_utc);

CREATE INDEX IF NOT EXISTS idx_noise_level_h_ts ON noise_level_h (ts_hour_kst);

CREATE INDEX idx_noise_ts ON noise_reading(ts_utc);

CREATE INDEX idx_noise_station ON noise_reading(station_id);

ALTER TABLE
    stations
ADD
    CONSTRAINT uq_stations_name UNIQUE (name);

ALTER TABLE
    noise_reading
ADD
    CONSTRAINT uq_noise_station_ts UNIQUE (station_id, ts_utc);