CREATE DATABASE IF NOT EXISTS noisemap;

CREATE TABLE stations (
    station_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    geom geometry(Point, 4326) NOT NULL
);

CREATE TABLE IF NOT EXISTS noise_reading (
    reading_id BIGSERIAL PRIMARY KEY,
    station_id INT NOT NULL,
    ts_utc TIMESTAMPTZ NOT NULL,
    db_level NUMERIC(5, 2) NOT NULL,
    part_of_day TEXT,
    src_month DATE GENERATED ALWAYS AS (
        date_trunc('month', ts_utc AT TIME ZONE 'UTC') :: date
    ) STORED,
    CONSTRAINT fk_noise_station FOREIGN KEY (station_id) REFERENCES stations(station_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_part_of_day CHECK (
        part_of_day IN ('day', 'night')
        OR part_of_day IS NULL
    ),
    CONSTRAINT uq_noise_station_ts UNIQUE (station_id, ts_utc)
);

CREATE INDEX idx_noise_ts ON noise_reading(ts_utc);

CREATE INDEX idx_noise_station ON noise_reading(station_id);

-- для stations (чтобы работал ON CONFLICT (name))
ALTER TABLE
    stations
ADD
    CONSTRAINT uq_stations_name UNIQUE (name);

-- для noise_reading (чтобы работал ON CONFLICT (station_id, ts_utc))
ALTER TABLE
    noise_reading
ADD
    CONSTRAINT uq_noise_station_ts UNIQUE (station_id, ts_utc);

-- дубли имён станций
SELECT
    name,
    COUNT(*)
FROM
    stations
GROUP BY
    name
HAVING
    COUNT(*) > 1;

-- дубли измерений по паре (station_id, ts_utc)
SELECT
    station_id,
    ts_utc,
    COUNT(*)
FROM
    noise_reading
GROUP BY
    station_id,
    ts_utc
HAVING
    COUNT(*) > 1;